### ISSUE TITLE
fråga! =)

### ISSUE THREAD

**Issue by sleepy1235** [patrik033/SwishBackend#1]
Hej! Kan du inte göra den här fejk swishen till en hemsida istället? Hade varit fett! =)

**Comment by patrik033** [comment]
> Hej! Kan du inte göra den här fejk swishen till en hemsida istället? Hade varit fett! =)

Planen är att göra det, iaf under ett tag. Men har för mycket kvar innan allt är  tillräckligt ”färdigt”.

**Comment by sleepy1235** [comment]
jaha.. okej.

**Comment by patrik033** [comment]
> jaha.. okej.

Finns en TODO sektion i readme filen där du kan se vad som är kvar att göra, är en rätt lång lista för tillfället.
